{% set name = "soxspipe" %}
{% set version = "0.13.5" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/soxspipe-{{ version }}.tar.gz
  sha256: d75ce2bbdea4efd092405653eafafc9f045d90a877153e4cdc9d52b9fa081901

build:
  entry_points:
    - soxspipe=soxspipe.cl_utils:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - pyyaml ==6.0.2
    - fundamentals ==2.7.2
    - astropy-base ==6.1.2
    - ccdproc ==2.4.2
    - docopt ==0.6.2
    - photutils ==1.13.0
    - matplotlib-base ==3.9.2
    - numpy ==2.1.0
    - unicodecsv ==0.14.1
    - pandas ==2.2.2
    - tabulate ==0.9.0
    - bottleneck ==1.4.0
    - multiprocess ==0.70.16
    - specutils ==1.16.0
    - humanize ==4.11.0

test:
  imports:
    - soxspipe
    - soxspipe.commonutils
    - soxspipe.recipes
  commands:
    - soxspipe --help
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/thespacedoctor/soxspipe
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: A python package and command-line tools to The data-reduction pipeline for the SOXS instrument
  doc_url: https://soxspipe.readthedocs.io
  dev_url: https://github.com/thespacedoctor/soxspipe

extra:
  recipe-maintainers:
    - thespacedoctor
