{% set name = "soxspipe" %}
{% set version = "0.11.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/soxspipe-{{ version }}.tar.gz
  sha256: 02f378fb014b7407a87c703782c4d661263da34ab4bf8bd227b412af96ab003b

build:
  entry_points:
    - soxspipe=soxspipe.cl_utils:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.11
    - setuptools
    - wheel
  run:
    - astropy ==6.1.2
    - bottleneck ==1.4.0
    - ccdproc ==2.4.2
    - docopt ==0.6.2
    - fundamentals ==2.7.2
    - matplotlib-base ==3.9.2
    - numpy ==2.1.0
    - pandas ==2.2.2
    - pathlib ==1.0.1
    - photutils ==1.13.0
    - python >=3.11
    - pyyaml ==6.0.2
    - tabulate ==0.9.0
    - unicodecsv ===0.14.1
    - multiprocess ==0.70.16
    - specutils ==1.16.0
]


test:
  imports:
    - soxspipe
    - soxspipe.commonutils
    - soxspipe.recipes
  commands:
    - soxspipe --help

about:
  home: https://github.com/thespacedoctor/soxspipe
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: A python package and command-line tools to The data-reduction pipeline for the SOXS instrument
  doc_url: https://soxspipe.readthedocs.io
  dev_url: https://github.com/thespacedoctor/soxspipe

extra:
  recipe-maintainers:
    - thespacedoctor
