{% set name = "soxspipe" %}
{% set version = "0.11.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/soxspipe-{{ version }}.tar.gz
  sha256: 2bb2fd4d7358fa2e740b40c78c4d2495e0b949d84cf303a26a48492891264111

build:
  entry_points:
    - soxspipe=soxspipe.cl_utils:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - astropy
    - bottleneck
    - ccdproc
    - docopt
    - fundamentals
    - matplotlib-base
    - numpy
    - pandas
    - pathlib
    - photutils
    - python >=3.9
    - pyyaml ==5.3.1
    - tabulate
    - unicodecsv
    - multiprocess
    - jinja2
    - specutils

test:
  imports:
    - soxspipe
    - soxspipe.commonutils
    - soxspipe.recipes
  commands:
    - soxspipe --help

about:
  home: https://github.com/thespacedoctor/soxspipe
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: A python package and command-line tools to The data-reduction pipeline for the SOXS instrument
  doc_url: https://soxspipe.readthedocs.io
  dev_url: https://github.com/thespacedoctor/soxspipe

extra:
  recipe-maintainers:
    - thespacedoctor
