{% set name = "soxspipe" %}
{% set version = "0.11.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/soxspipe-{{ version }}.tar.gz
  sha256: 50ec35515db71daec53f006489a3b2060166f8458eab0a8f5d3fe7549e638dde

build:
  entry_points:
    - soxspipe=soxspipe.cl_utils:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.11
    - setuptools
    - wheel
  run:
    - astropy 6.1.*
    - bottleneck 1.4.*
    - ccdproc 2.4.*
    - docopt 0.6.*
    - fundamentals 2.7.*
    - matplotlib-base 3.9.*
    - numpy 2.1.*
    - pandas 2.2.*
    - pathlib 1.0.*
    - photutils 1.13.*
    - python >=3.11
    - pyyaml 6.0.*
    - tabulate 0.9.*
    - unicodecsv 0.14.*
    - multiprocess 0.70.*
    - specutils 1.16.*
]


test:
  imports:
    - soxspipe
    - soxspipe.commonutils
    - soxspipe.recipes
  commands:
    - soxspipe --help

about:
  home: https://github.com/thespacedoctor/soxspipe
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: A python package and command-line tools to The data-reduction pipeline for the SOXS instrument
  doc_url: https://soxspipe.readthedocs.io
  dev_url: https://github.com/thespacedoctor/soxspipe

extra:
  recipe-maintainers:
    - thespacedoctor
